project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('record/', include('record.urls')),
    
    
]

record/urls.py
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 10 22:21:07 2021

@author: nagat
"""

from django.urls import path
from . import views

app_name = 'record'

urlpatterns = [
    path('',views.index, name='index'), #/record
    path('add/',views.add, name='add'), #/record/add
    path('next_matrix/',views.next_matrix, name='next_matrix'), #/record/next
    path('update/<int:pk>/',views.update, name='update'), #/record/update/1
    path('delete/<int:pk>/',views.delete, name='delete'), #/record/delete/1
    path('all_delete/',views.all_delete, name='all_delete'), #/record/delete/1

]

record/models.py
from django.db import models
from django.utils import timezone

class Day(models.Model):
    date = models.DateTimeField('日付',default=timezone.now)
    number = models.IntegerField('出目',default=0)
    types = models.IntegerField('ルーレットタイプ',default=1)
    place = models.TextField('場所',default=0, max_length=10)
    company = models.TextField('製作会社',default=0, max_length=10)
    

record/forms.py
from django import forms
from.models import Day

class DayCreateForm(forms.ModelForm):
    
    class Meta:
        model = Day
        fields = '__all__'

record/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DayCreateForm
from .models import Day
from django_pandas.io import read_frame
import numpy as np

def index(request):
    context = {
        'list':Day.objects.all()
    }
    return render(request, 'record/list.html',context)

def add(request):
    form = DayCreateForm(request.POST or None)
    if request.method =='POST' and form.is_valid():
        form.save()
        return redirect('record:index')
 
    context = {
        'form':DayCreateForm()
    }
    return render(request,'record/form.html',context)



def update(request, pk):
    day = get_object_or_404(Day, pk=pk)
    form = DayCreateForm(request.POST or None, instance = day)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('record:index')
    
    context = {
        'form':form
    }
    return render(request,'record/form.html', context)

def delete(request, pk):
    day = get_object_or_404(Day, pk=pk)
    if request.method == 'POST':
        day.delete()
        return redirect('record:index')
    
    context = {
        'day':day
    }
    return render(request,'record/day_delete_confirm.html', context)


def all_delete(request):
    if request.method == 'POST':
        Day.objects.all().delete()

    context= {}

    return render(request,'record/all_delete_confirm.html', context)

def next_matrix(request):
    if request.method == 'POST':
        Days = Day.objects.all()
        df_all = read_frame(Days, fieldnames = ['date', 'number', 'types', 'place', 'company'])
        df = df_all.number

        count_matrix = np.zeros((38,38))
        neighbor_matrix = np.array([[	0	,	35	,	14	,	2	,	0	,	28	,	9	,	26	],
[	1	,	24	,	36	,	13	,	1	,	37	,	27	,	10	],
[	2	,	23	,	35	,	14	,	2	,	0	,	28	,	9	],
[	3	,	22	,	34	,	15	,	3	,	24	,	36	,	13	],
[	4	,	21	,	33	,	16	,	4	,	23	,	35	,	14	],
[	5	,	20	,	32	,	17	,	5	,	22	,	34	,	15	],
[	6	,	19	,	31	,	18	,	6	,	21	,	33	,	16	],
[	7	,	26	,	30	,	11	,	7	,	20	,	32	,	17	],
[	8	,	25	,	29	,	12	,	8	,	19	,	31	,	18	],
[	9	,	2	,	0	,	28	,	9	,	26	,	30	,	11	],
[	10	,	1	,	37	,	27	,	10	,	25	,	29	,	12	],
[	11	,	9	,	26	,	30	,	11	,	7	,	20	,	32	],
[	12	,	10	,	25	,	29	,	12	,	8	,	19	,	31	],
[	13	,	3	,	24	,	36	,	13	,	1	,	37	,	27	],
[	14	,	4	,	23	,	35	,	14	,	2	,	0	,	28	],
[	15	,	5	,	22	,	34	,	15	,	3	,	24	,	36	],
[	16	,	6	,	21	,	33	,	16	,	4	,	23	,	35	],
[	17	,	7	,	20	,	32	,	17	,	5	,	22	,	34	],
[	18	,	8	,	19	,	31	,	18	,	6	,	21	,	33	],
[	19	,	29	,	12	,	8	,	19	,	31	,	18	,	6	],
[	20	,	30	,	11	,	7	,	20	,	32	,	17	,	5	],
[	21	,	31	,	18	,	6	,	21	,	33	,	16	,	4	],
[	22	,	32	,	17	,	5	,	22	,	34	,	15	,	3	],
[	23	,	33	,	16	,	4	,	23	,	35	,	14	,	2	],
[	24	,	34	,	15	,	3	,	24	,	36	,	13	,	1	],
[	25	,	37	,	27	,	10	,	25	,	29	,	12	,	8	],
[	26	,	0	,	28	,	9	,	26	,	30	,	11	,	7	],
[	27	,	13	,	1	,	37	,	27	,	10	,	25	,	29	],
[	28	,	14	,	2	,	0	,	28	,	9	,	26	,	30	],
[	29	,	27	,	10	,	25	,	29	,	12	,	8	,	19	],
[	30	,	28	,	9	,	26	,	30	,	11	,	7	,	20	],
[	31	,	12	,	8	,	19	,	31	,	18	,	6	,	21	],
[	32	,	11	,	7	,	20	,	32	,	17	,	5	,	22	],
[	33	,	18	,	6	,	21	,	33	,	16	,	4	,	23	],
[	34	,	17	,	5	,	22	,	34	,	15	,	3	,	24	],
[	35	,	16	,	4	,	23	,	35	,	14	,	2	,	0	],
[	36	,	15	,	3	,	24	,	36	,	13	,	1	,	37	],
[	37	,	36	,	13	,	1	,	37	,	27	,	10	,	25	]],
)
        results_matrix = np.array([[	2	,	0	],
[	0	,	0	],
[	28	,	0	],
[	9	,	0	],
[	26	,	0	],
[	30	,	0	],
[	11	,	0	],
[	7	,	0	],
[	20	,	0	],
[	32	,	0	],
[	17	,	0	],
[	5	,	0	],
[	22	,	0	],
[	34	,	0	],
[	15	,	0	],
[	3	,	0	],
[	24	,	0	],
[	36	,	0	],
[	13	,	0	],
[	1	,	0	],
[	37	,	0	],
[	27	,	0	],
[	10	,	0	],
[	25	,	0	],
[	29	,	0	],
[	12	,	0	],
[	8	,	0	],
[	19	,	0	],
[	31	,	0	],
[	18	,	0	],
[	6	,	0	],
[	21	,	0	],
[	33	,	0	],
[	16	,	0	],
[	4	,	0	],
[	23	,	0	],
[	35	,	0	],
[	14	,	0	]])


        
        df = df.replace(100, 37)
        df_length = len(df)-1
        now1 = df.tail(1)
        now = now1.iloc[0]
        next_numbers = count_matrix[now,:]
        
        for i in range(1, df_length):
            x = df.iloc[i]
            y = df.iloc[i-  1]
            
            for j in range(1,8):
                count_matrix[y,neighbor_matrix[x,j]] = count_matrix[y,neighbor_matrix[x,j]] + 1
                  
        for l in range(38):
            m = results_matrix[l,0]   
            n = next_numbers[m]    
            results_matrix[l,1] = n
    
        results = results_matrix         
        my_app = {'result' : results}
        return render(request,'record/next_matrix.html', my_app)

    context = {}
    return render(request,'record/next_matrix.html', context)

record/templates/record/all_delete_confirm.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>出目の記録取得</title>
  </head>
  <body>
{% extends 'record/base.html' %}
    {% block content%}
    <form action = "" method="POST">
    <text　class="text">Are you sure??</text>

    <button type = "submit" class="btn btn-primary">全削除</button>
    {% csrf_token%}
    </form>
    {% endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

record/templates/record/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>出目の記録取得</title>
  </head>
  <body>
   <div class="container">  
    <nav class="nav">
      <a class="nav-link" href="{% url 'record:index' %}">一覧</a>
      <a class="nav-link" href="{% url 'record:add' %}">追加</a>
      <a class="nav-link" href="{% url 'record:next_matrix' %}">予想</a>
      <a class="nav-link" href="{% url 'record:all_delete' %}">※全削除※</a>
    </nav>
    {% block content%}
    {% endblock%}
   <div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

record/templates/record/day_delete_confirm.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>出目の記録取得</title>
  </head>
  <body>
{% extends 'record/base.html' %}
    {% block content%}
    <form action = "" method="POST">
    <table class="table">
     <tr>
      <th>日付</th>
      <td>{{day.date}}</td>
     </tr>
     <tr>
      <th>出目</th>
      <td>{{day.number}}</td>
     </tr>
     <tr>
      <th>ルーレットタイプ</th>
      <td>{{day.types}}</td>
     </tr>
     <tr>
      <th>場所</th>
      <td>{{day.place}}</td>
     </tr>
     <tr>
      <th>製造会社</th>
      <td>{{day.company}}</td>
     </tr>
    </table>

    <button type = "submit" class="btn btn-primary">この入力を削除</button>
    {% csrf_token%}
    </form>
    {% endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

record/templates/record/form.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>出目の記録取得</title>
  </head>
  <body>
{% extends 'record/base.html' %}
    {% block content%}
    <form action = "" method="POST">
    <table class="table">
     <tr>
      <th>日付</th>
      <td>{{form.date}}</td>
     </tr>
     <tr>
      <th>出目</th>
      <td>{{form.number}}</td>
     </tr>
     <tr>
      <th>ルーレットタイプ</th>
      <td>{{form.types}}</td>
     </tr>
     <tr>
      <th>場所</th>
      <td>{{form.place}}</td>
     </tr>
     <tr>
      <th>製造会社</th>
      <td>{{form.company}}</td>
     </tr>
    </table>

    <button type = "submit" class="btn btn-primary">送信</button>
    {% csrf_token%}
    </form>
    {% endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

record/templates/record/list.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>出目の記録取得</title>
  </head>
  <body>
 
{% extends 'record/base.html' %}
{% block content%}
{% for day in Day %}
    <h2>{{Day.date}}</h2>
{% endfor %}

 <table border ="1", class="table">
  <thread>
   <tr>
       <th>日付</th>
       <th>出目</th>
       <th>タイプ</th>
       <th>場所</th>
       <th>製作</th>
       <th>#</th>
       <th>#</th>
      
   </tr>
 </thead>
 <tbody>
  {% for day in list %}
   <tr> 
       <td>{{day.date}}</td>
       <td>{{day.number}}</td>   
       <td>{{day.types}}</td>   
       <td>{{day.place}}</td>   
       <td>{{day.company}}</td>   
       <td><a href="{% url 'record:update' day.pk %}">更新</a></td>  
       <td><a href="{% url 'record:delete' day.pk %}">削除</a></td>   
   </tr>    
  {% endfor %}
 </table>
 {% endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

record/templates/record/next_matrix.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>出目の記録取得</title>
  </head>
  <body>
{% extends 'record/base.html' %}
    {% block content%}
    <form action = "" method="POST">

    <button type = "submit" class="btn btn-primary">予想</button>
    <p>ここに{{result}}来てほしい</p>
    
    
    
    {% csrf_token%}
    </form>
    {% endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>